import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });
import "react-toastify/dist/ReactToastify.css";

import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const locales = ["en", "ar"];
import "../globals.css";
import QueryProvider from "../utils/QueryProvider";
import { NextIntlClientProvider } from "next-intl";
import { ToastContainer } from "react-toastify";

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body style={{ textAlign: locale === "ar" ? "right" : "left" }} className={`${inter.className}`}>
        <ToastContainer position="top-center" theme="dark" />

        <QueryProvider>
          <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
