import type { Metadata } from "next";
import AuthProvider from "../../utils/AuthProvider";
import { ModeToggle } from "../../components/Toggle";
import MaxWidthWrapper from "../../components/MaxWidthWrapper";
import LogoutButton from "../../components/LogoutButton";
import SideBar from "../../components/SideBar";
import { ThemeProvider } from "../../context/ThemeProvider";
import { unstable_setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);

  return (
    <main>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <MaxWidthWrapper>
          <nav className=" flex items-center justify-between">
            <ModeToggle />
            <LogoutButton />
          </nav>
        </MaxWidthWrapper>
        <AuthProvider>
          <MaxWidthWrapper noPadding className=" grid grid-cols-10">
            <div className="col-span-2">
              <SideBar />
            </div>
            <div className="col-span-8">{children}</div>
          </MaxWidthWrapper>
        </AuthProvider>
      </ThemeProvider>
    </main>
  );
}
